<a href="https://colab.research.google.com/github/swapnilsethi/Stat-5000/blob/main/Model_design_and_Predications.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [120]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import cm
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
import sklearn
import math
import sys
np.set_printoptions(threshold=sys.maxsize)
pd.pandas.set_option('display.max_columns',None)
from google.colab import files

In [121]:
#URL = ("https://raw.githubusercontent.com/swapnilsethi/Stat-5000/master/X_train.csv")
data = pd.read_csv('X_train.csv')

In [122]:
data.head()

,Unnamed: 0,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontage_nan,MasVnrArea_nan,BsmtFinSF1_nan,BsmtFinSF2_nan,BsmtUnfSF_nan,TotalBsmtSF_nan,BsmtFullBath_nan,BsmtHalfBath_nan,GarageYrBlt_nan,GarageCars_nan,GarageArea_nan
0,0,1,208500,60,2,65,8450,1,0,1,1,0,0,11,2,1,4,5,7,5,5,5,0,0,6,6,2,196,2,2,3,2,2,0,5,706,3,0,150,856,1,4,1,2,856,854,0,1710,1,0,2,1,3,1,2,8,3,0,1,2,5,1,2,548,1,2,2,0,61,0,0,0,0,0,2,2008,2,2,0,0,0,0,0,0,0,0,0,0,0
1,1,2,181500,20,2,80,9600,1,0,1,1,1,0,8,1,1,4,4,6,8,31,31,0,0,1,1,1,0,1,2,2,2,2,3,3,978,3,0,284,1262,1,4,1,2,1262,0,0,1262,0,1,2,0,3,1,1,6,3,1,2,2,31,1,2,460,1,2,2,298,0,0,0,0,0,0,5,2007,2,2,0,0,0,0,0,0,0,0,0,0,0
2,2,3,223500,60,2,68,11250,1,1,1,1,0,0,11,2,1,4,5,7,5,7,6,0,0,6,6,2,162,2,2,3,2,2,1,5,486,3,0,434,920,1,4,1,2,920,866,0,1786,1,0,2,1,3,1,2,6,3,1,2,2,7,1,2,608,1,2,2,0,42,0,0,0,0,0,9,2008,2,2,0,0,0,0,0,0,0,0,0,0,0
3,3,4,140000,70,2,60,9550,1,1,1,1,2,0,12,2,1,4,5,7,5,91,36,0,0,2,2,1,0,1,2,1,1,3,0,3,216,3,0,540,756,1,3,1,2,961,756,0,1717,1,0,1,0,3,1,2,7,3,1,1,0,8,0,3,642,1,2,2,0,35,272,0,0,0,0,2,2006,2,0,0,0,0,0,0,0,0,0,0,0,0
4,4,5,250000,60,2,84,14260,1,1,1,1,1,0,16,2,1,4,5,8,5,8,8,0,0,6,6,2,350,2,2,3,2,2,2,5,655,3,0,490,1145,1,4,1,2,1145,1053,0,2198,1,0,2,1,4,1,2,9,3,1,2,2,8,1,3,836,1,2,2,192,84,0,0,0,0,0,12,2008,2,2,0,0,0,0,0,0,0,0,0,0,0

In [123]:
train_x = data.iloc[:1300, 3:].values 
#print(x)
train_y = data.iloc[:1300,2].values 
train_test_x = data.iloc[1301:, 3:].values 
train_test_y = data.iloc[1301:,2].values 

#print(y)
#data.shape

In [124]:
#URL = "https://raw.githubusercontent.com/swapnilsethi/Stat-5000/master/X_test.csv"

test_data = pd.read_csv('X_test.csv')

In [125]:
test_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontage_nan,MasVnrArea_nan,BsmtFinSF1_nan,BsmtFinSF2_nan,BsmtUnfSF_nan,TotalBsmtSF_nan,BsmtFullBath_nan,BsmtHalfBath_nan,GarageYrBlt_nan,GarageCars_nan,GarageArea_nan
0,0,1461,20,0,80.0,11622,1,0,1,1,0,0,5,1,1,4,4,5,6,49,49,0,0,6,6,1,0.0,1,2,2,1,2,0,0,468.0,1,144.0,270.0,882.0,1,2,1,2,896,0,0,896,0.0,0.0,1,0,2,1,1,5,3,0,1,2,49.0,0,1.0,730.0,1,2,2,140,0,0,0,120,0,0,6,2010,2,2,0,0,0,0,0,0,0,0,0,0,0
1,1,1462,20,2,81.0,14267,1,1,1,1,2,0,5,2,1,4,4,6,6,52,52,2,0,2,0,2,108.0,1,2,2,1,2,0,3,923.0,3,0.0,406.0,1329.0,1,2,1,2,1329,0,0,1329,0.0,0.0,1,1,3,1,2,6,3,0,1,2,52.0,0,1.0,312.0,1,2,2,393,36,0,0,0,0,12500,6,2010,2,2,0,0,0,0,0,0,0,0,0,0,0
2,2,1463,60,2,74.0,13830,1,1,1,1,0,0,10,2,1,4,5,5,5,13,12,0,0,6,6,1,0.0,1,2,3,2,2,0,5,791.0,3,0.0,137.0,928.0,1,3,1,2,928,701,0,1629,0.0,0.0,2,1,3,1,1,6,3,1,2,2,13.0,2,2.0,482.0,1,2,2,212,34,0,0,0,0,0,3,2010,2,2,0,0,0,0,0,0,0,0,0,0,0
3,3,1464,60,2,78.0,9978,1,1,1,1,0,0,10,2,1,4,5,6,6,12,12,0,0,6,6,2,20.0,1,2,3,1,2,0,5,602.0,3,0.0,324.0,926.0,1,4,1,2,926,678,0,1604,0.0,0.0,2,1,3,1,2,7,3,1,1,2,12.0,2,2.0,470.0,1,2,2,360,36,0,0,0,0,0,6,2010,2,2,0,0,0,0,0,0,0,0,0,0,0
4,4,1465,120,2,43.0,5005,1,1,3,1,0,0,8,2,1,3,4,8,5,18,18,0,0,3,4,1,0.0,2,2,3,2,2,0,3,263.0,3,0.0,1017.0,1280.0,1,4,1,2,1280,0,0,1280,0.0,0.0,2,0,2,1,2,5,3,0,1,2,18.0,1,2.0,506.0,1,2,2,0,82,0,0,144,0,0,1,2010,2,2,0,0,0,0,0,0,0,0,0,0,0

In [126]:
test_data.shape

(1459, 88)

In [127]:
test_x = test_data.iloc[:, 2:].values

#test_x

In [128]:
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)

In [129]:
regressor.fit(train_x, train_y)

RandomForestRegressor(random_state=0)

In [114]:
#Y_pred = regressor.predict(test_x)

Random Search Cross Validation

In [130]:
from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(regressor.get_params())

Parameters currently in use:

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

In [131]:
#https://towardsdatascience.com/hyperparameter-tuning-the-random-forest-in-python-using-scikit-learn-28d2aa77dd74
#Random Hyperparameter Grid
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [100, 311, 522, 733, 944, 1155, 1366, 1577, 1788, 2000]}

In [132]:
#Random Search Training
# Use the random grid to search for best hyperparameters
# First create the base model to tune
regressor = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid, n_iter = 100, cv = 5, verbose=5, random_state=42, n_jobs = 5)
# Fit the random search model
rf_random.fit(train_x, train_y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_iter=100,
                   n_jobs=5,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 311, 522, 733,
                                                         944, 1155, 1366, 1577,
                                                         1788, 2000]},
                   random_state=42, verbose=5)

In [133]:
rf_random.best_params_

{'bootstrap': False,
 'max_depth': None,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 311}

In [134]:
regressor = RandomForestRegressor(bootstrap= False,
 max_depth= None,
 max_features= 'sqrt',
 min_samples_leaf= 1,
 min_samples_split= 2,
 n_estimators= 311)
regressor.fit(train_x, train_y)

RandomForestRegressor(bootstrap=False, max_features='sqrt', n_estimators=311)

In [135]:
Y_pred = regressor.predict(test_x)

In [136]:
#Evaluate Random Search
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy
base_model = RandomForestRegressor(n_estimators = 10, random_state = 42)
base_model.fit(train_x, train_y)
base_accuracy = evaluate(base_model, train_test_x, train_test_y)

Model Performance
Average Error: 18886.8245 degrees.
Accuracy = 88.38%.

In [137]:
best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random, train_test_x, train_test_y)

Model Performance
Average Error: 16007.3200 degrees.
Accuracy = 89.99%.

In [138]:
print('Improvement of {:0.2f}%.'.format( 100 * (random_accuracy - base_accuracy) / base_accuracy))

Improvement of 1.81%.

Grid Search with Cross Validation

In [64]:
'''
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [False],
    'max_depth': [80, 90, 100, 110],
    'max_features': ['sqrt'],
    'min_samples_leaf': [1,2, 3, 4],
    'min_samples_split': [5,7,8, 10],
    'n_estimators': [100, 500, 700, 900]
}
# Create a based model
rf = RandomForestRegressor()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 5, n_jobs = 5, verbose = 5)'''

In [ ]:
# Fit the grid search to the data
'''grid_search.fit(train_x, train_y)'''

Fitting 5 folds for each of 256 candidates, totalling 1280 fits

GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=5,
             param_grid={'bootstrap': [False], 'max_depth': [80, 90, 100, 110],
                         'max_features': ['sqrt'],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [5, 7, 8, 10],
                         'n_estimators': [100, 500, 700, 900]},
             verbose=5)

In [ ]:
'''grid_search.best_params_'''

{'bootstrap': False,
 'max_depth': 100,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 700}

In [ ]:
'''best_grid = grid_search.best_estimator_
grid_accuracy = evaluate(best_grid, train_test_x, train_test_y)'''

Model Performance
Average Error: 15705.8844 degrees.
Accuracy = 90.24%.

In [ ]:
'print('Improvement of {:0.2f}%.'.format( 100 * (grid_accuracy - base_accuracy) / base_accuracy))'

Improvement of 1.86%.

In [ ]:
'''regressor = RandomForestRegressor(bootstrap= False,
 max_depth= 100,
 max_features= 'sqrt',
 min_samples_leaf= 1,
 min_samples_split= 5,
 n_estimators= 700)
regressor.fit(train_x, train_y)'''

RandomForestRegressor(bootstrap=False, max_depth=100, max_features='sqrt',
                      min_samples_split=5, n_estimators=700)

In [ ]:
'''Y_pred = regressor.predict(test_x)'''

In [ ]:
#mse = sklearn.metrics.mean_squared_error(test_y, Y_pred)

In [ ]:
#rmse = math.sqrt(mse)
#print(rmse)

In [139]:
ID = test_data.iloc[:, 1].values

In [140]:
pred = pd.DataFrame(ID, columns=['Id'])

In [ ]:
#Y_pred_unscale = np.exp(Y_pred)

In [141]:
pred['SalePrice'] = Y_pred.tolist()

In [142]:
pred

        Id      SalePrice
0     1461  125659.556270
1     1462  150935.659164
2     1463  181814.260450
3     1464  188017.202572
4     1465  189528.681672
...    ...            ...
1454  2915   88181.511254
1455  2916   88246.167203
1456  2917  161140.517685
1457  2918  116839.022508
1458  2919  220976.311897

[1459 rows x 2 columns]

In [ ]:
from google.colab import files
pred.to_csv('pred.csv')
files.download('pred.csv')